spring:
  application:
    name: video
  data:
    mongodb:
      host: 192.168.0.230
      port: 27017
      username: admin
      password: 123456
    redis:
      host: 192.168.0.230
      port: 6379
